//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard
#include "pch.h" // precompiler header
#include "automation.h" // class's header file

// ----------------------------------------- Automation manager --------------

// null songleton
SA::AutomationManager* SA::AutomationManager::s_singleton = 0;

SA::AutomationManager& SA::AutomationManager::get_instance()
{
	if(s_singleton == 0) {
		s_singleton = new SA::AutomationManager();
	}
	return *s_singleton;
}

void SA::AutomationManager::destroy_instance()
{
	if(s_singleton) {
		delete s_singleton;
		s_singleton = 0;
	}
}

// -------------

// class constructor
SA::AutomationManager::AutomationManager()
{
	// start the timer // 5 miliseconds interval
	// sort out stopwatch
	// get accurate timing
}

// class destructor
SA::AutomationManager::~AutomationManager()
{
}

void SA::AutomationManager::add_automated_object(AutomatedObject* object)
{
	m_automatedList.push_back(object);
}
void SA::AutomationManager::remove_automated_object(AutomatedObject* object)
{
	// remove object
	m_automatedList.remove(object);
}


void SA::AutomationManager::tick(float dT)
{
	for(std::list<AutomatedObject*>::iterator i = m_automatedList.begin(); i != m_automatedList.end(); i++) {
		(*i)->tick(dT);
	}
}

// --------------------------------------- Automated Object ----------------------
SA::AutomatedObject::AutomatedObject()
{
	SA::AutomationManager::get_instance().add_automated_object(this);
}

SA::AutomatedObject::~AutomatedObject()
{
	SA::AutomationManager::get_instance().remove_automated_object(this);
}
