//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard

#ifndef SA_BASEBEHAVIOUR_H
#define SA_BASEBEHAVIOUR_H

// A selection of basic beahviours
namespace SA
{

// function to register the behaviours in this file
void RegisterBaseBehaviours(BehaviourManager* theManager);

// basic group behaviour
// uses first set of collective
class BPGroup : public Behaviour
{
public:
	static Behaviour* Factory()
	{
		return new BPGroup;
	};
	// class constructor
	BPGroup();
	// class destructor
	~BPGroup();
};

// multi cross fade
// uses first set of collective
class BMultiCrossfade : public Behaviour
{
public:
	static Behaviour* Factory()
	{
		return new BMultiCrossfade;
	};
	// class constructor
	BMultiCrossfade();
	// class destructor
	~BMultiCrossfade();
};

// wave behaviour
class BWave : public Behaviour, public AutomatedObject
{
public:
	static Behaviour* Factory()
	{
		return new BWave;
	};
	// class constructor
	BWave();
	// class destructor
	~BWave();

	// overloaded
	virtual void tick(float dT);

private:
	float angle;
	ParameterPtr m_amp;
	ParameterPtr m_freq;

};

// wave behaviour
class BMexicanWave : public Behaviour, public AutomatedObject
{
public:
	static Behaviour* Factory()
	{
		return new BMexicanWave;
	};
	// class constructor
	BMexicanWave();
	// class destructor
	~BMexicanWave();

	// overloaded
	virtual void tick(float dT);

private:
	float angle;
	ParameterPtr m_amp;
	ParameterPtr m_freq;

};

// wave behaviour
class BRandom : public Behaviour, public AutomatedObject
{
	ParameterPtr m_amp;
	ParameterPtr m_freq;
public:
	static Behaviour* Factory()
	{
		return new BRandom;
	};
	// class constructor
	BRandom();
	// class destructor
	~BRandom();

	// overloaded
	virtual void tick(float dT);
};

}
#endif // SA_BASEBEHAVIOUR_H
