//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard
#include "pch.h" // precompiler header


#include "automation.h"
#include "pvar.h" // class's header file


#include "behaviour.h"
#include "amclient.h"
#include "vumeterwidget.h"
#include "monitornodewidget.h"
#include "pvarwidgets.h"

#include "behaviourview.h" // class's header file
#include <sstream>

#include "performance.h"
//------------------------------------------ BehaviourViewItem ----------------------------
//events
BEGIN_EVENT_TABLE(Resound::BehaviourViewItem, wxPanel)
EVT_BUTTON(BSID_RENAME, Resound::BehaviourViewItem::OnRename)
END_EVENT_TABLE()

// class constructor
Resound::BehaviourViewItem::BehaviourViewItem(wxWindow* parent, int id, BehaviourPtr b)
		: wxPanel(parent, id)
{
	behaviour = b;

	SetWindowStyle(wxNO_BORDER | wxCLIP_CHILDREN);
	SetBackgroundColour(wxColour(30,100,150));
	SetForegroundColour(wxColour(255,255,255));

	// construct the sub objects and sizer
	wxSizer* topSizer = new wxBoxSizer( wxVERTICAL );
	label = new wxStaticText(this,-1,wxString(wxConvertMB2WX(behaviour->get_name().c_str())));
	topSizer->Add(label);

	wxSizer* sizer = new wxBoxSizer( wxHORIZONTAL );

	//sizer->Add(new wxButton(this,BSID_EDITOR,_("Editor")));
	//sizer->Add(new wxButton(this,BSID_RENAME,_("Rename")));
	collectiveWidget = new Resound::CollectiveWidget(this,-1,_T("Assign"), &behaviour->get_collective(), true);
	sizer->Add(collectiveWidget);

	// FIXME drastic changes to the way behaviours register parameters
	for(int n = 0; n < behaviour->get_num_parameters(); n++) { 
		std::stringstream s;
		s << "/bm/" << behaviour->get_name() << "/" << behaviour->get_parameter(n)->get_name();
		sizer->Add(new Resound::MonitorNodeWidget(this,-1,ParameterAddress(s.str()))); // FIXME behaviour parameter addressing
	}

	topSizer->Add(sizer);

	// layout
	SetSizer(topSizer);
	topSizer->SetSizeHints(this);   // set size hints to honour minimum size
	topSizer->Layout();
}


// class destructor
Resound::BehaviourViewItem::~BehaviourViewItem()
{
	// insert your code here
}
void Resound::BehaviourViewItem::OnRename(wxCommandEvent &event)
{
	wxString nm(wxConvertMB2WX(behaviour->get_name().c_str()));
	behaviour->set_name((const char*)wxConvertWX2MB(wxGetTextFromUser(_("Enter a new name for this behaviour"),_("Name Behaviour"),nm))); // FIXME string conversion FIXED
	label->SetLabel(nm); // FIXME string conversion FIXED
}
//----------------------------------------- BehaviourView ---------------------------------
//events
BEGIN_EVENT_TABLE(Resound::BehaviourView, wxScrolledWindow)
EVT_BUTTON( BSID_CREATE, Resound::BehaviourView::OnCreateBehaviour)
END_EVENT_TABLE()

// class constructor
Resound::BehaviourView::BehaviourView(wxWindow* parent, int id)
		: wxScrolledWindow(parent, id, wxPoint(0,0), wxSize(320,240))
{
	// construct the sub objects and sizer
	topSizer = new wxBoxSizer( wxVERTICAL );

	topSizer->Add(new wxStaticText(this,-1,_("Behaviour panel")));
	topSizer->Add(new wxButton(this,BSID_CREATE,_("Create Behaviour")));


	// build the dynamic section of the panel
	behaviourSizer = new wxBoxSizer( wxVERTICAL );
	topSizer->Add(behaviourSizer);

	// layout
	SetSizer(topSizer);
	topSizer->SetSizeHints(this);   // set size hints to honour minimum size
	topSizer->Layout();
}


// class destructor
Resound::BehaviourView::~BehaviourView()
{
	// insert your code here
}

void Resound::BehaviourView::BuildPanel()
{
	Resound::BehaviourManager* behaviourManager = dynamic_cast<Resound::BehaviourManager*>(&RESOUND_NAMESPACE()->get_parameter_namespace(1));
	// build of the panel
	behaviourSizer->Remove(0); // remove old sizer
	wxBoxSizer* sizer = new wxBoxSizer( wxVERTICAL );
	behaviourSizer->Add(sizer);
	for(BehaviourMap::iterator i = behaviourManager->get_behaviour_map().begin(); i !=  behaviourManager->get_behaviour_map().end(); i++) {
		int id = (*i).first;
		BehaviourPtr b = (*i).second;
		sizer->Add(new BehaviourViewItem(this,-1,b));
	}
	topSizer->SetSizeHints(this);   // set size hints to honour minimum size
	topSizer->Layout();
}

void Resound::BehaviourView::OnCreateBehaviour(wxCommandEvent &event)
{
	Resound::BehaviourManager* behaviourManager = dynamic_cast<Resound::BehaviourManager*>(&RESOUND_NAMESPACE()->get_parameter_namespace(1));
	try {
		behaviourManager->create_behaviour();
	} catch(Resound::CreateBehaviourException& e) {
		//Cancel was pressed so ignore this exception here.
	}
	BuildPanel();
}
