//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard

#ifndef BEHAVIOURVIEW_H
#define BEHAVIOURVIEW_H
#include "behaviour.h"
namespace Resound
{

// Behaviour selection panel 
enum BSID
{
    BSID_CREATE = 1,
    BSID_EDITOR,
    BSID_RENAME,
    BSID_REMOVE
};
class BehaviourSelectPanel : public PVSSelectPanel
{
public:
	BehaviourSelectPanel(wxWindow* parent, ParameterNamespace* _subSystem);
	void BuildPanel();
private:
	wxBoxSizer *topSizer;
	wxBoxSizer *behaviourSizer;
	// events
	void OnCreateBehaviour(wxCommandEvent &event);
	DECLARE_EVENT_TABLE()
};

// item class used in behaviour view
class BehaviourViewItem : public wxPanel
{
public:
	// class constructor
	BehaviourViewItem(wxWindow* parent, int id, BehaviourPtr b);
	// class destructor
	~BehaviourViewItem();
private:

	CollectiveWidget* collectiveWidget; // a collective widget for this behaviour view
	BehaviourPtr behaviour;
	wxStaticText* label;
	DECLARE_EVENT_TABLE()
};

// view class for behaviour manager
class BehaviourView : public wxScrolledWindow
{
public:
	// class constructor
	BehaviourView(wxWindow* parent, int id);
	// class destructor
	~BehaviourView();	
	// build view
	void BuildPanel();
	void OnRemove(wxCommandEvent &event);
private:

	wxSizer* behaviourSizer;
	wxSizer* topSizer;
	std::list<wxWindow*> m_windowList;



	// event handling macro
	void OnCreateBehaviour(wxCommandEvent &event);
	DECLARE_EVENT_TABLE()
};

}
#endif // BEHAVIOURVIEW_H
