//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard

#ifndef BEHAVIOURVIEW_H
#define BEHAVIOURVIEW_H

namespace Resound
{
// item class used in behaviour view
class BehaviourViewItem : public wxPanel
{
public:
	// class constructor
	BehaviourViewItem(wxWindow* parent, int id, BehaviourPtr b);
	// class destructor
	~BehaviourViewItem();
private:

	CollectiveWidget* collectiveWidget; // a collective widget for this behaviour view
	BehaviourPtr behaviour;
	wxStaticText* label;
	void OnRename(wxCommandEvent &event);
	DECLARE_EVENT_TABLE()
};

// view class for behaviour manager
class BehaviourView : public wxScrolledWindow
{
public:
	// class constructor
	BehaviourView(wxWindow* parent, int id, BehaviourManager* manager);
	// class destructor
	~BehaviourView();
private:

	BehaviourManager *behaviourManager;
	wxSizer* behaviourSizer;
	wxSizer* topSizer;



	// build view
	void BuildPanel();
	// event handling macro
	void OnCreateBehaviour(wxCommandEvent &event);
	DECLARE_EVENT_TABLE()
};

}
#endif // BEHAVIOURVIEW_H
