//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard

#ifndef SAFADER_H
#define SAFADER_H

namespace SA
{
// custom event send by fader object
DECLARE_EVENT_TYPE(saEVT_FADER_CHANGED, -1)
// respond macro - EVT_COMMAND  (ID_MY_WINDOW, saEVT_FADER_CHANGED, MyFrame::OnMyEvent)
// respond range macro - EVT_COMMAND_RANGE  (ID_Lower, ID_Upper, saEVT_FADER_CHANGED, MyFrame::OnMyEvent)
// GUI Fader class suitable for audio projects
class FaderWidget : public wxControl
{
public:
	// class constructor
	FaderWidget(wxWindow *parent, int id, int _val, int _min, int _max);
	// class destructor
	~FaderWidget();


	void SetValue(int _val);
	int GetValue();
	void SetRange(int _min, int _max);

	void Tick(float dT); // time elapsed function for decay
private:
	wxBitmap bmFaderBack;
	wxBitmap bmFaderKnob;
	wxMemoryDC dcFaderBack;
	wxMemoryDC dcFaderKnob;
	int sizeX;
	int sizeY; // background bitmap size
	int kSizeX;
	int kSizeY; // knob bitmap size
	int trackYBegin;
	int trackYSize; // knob track size is less than the bitmap

	// slider values
	int val;
	int min, max;

	// events handled
	void OnPaint(wxPaintEvent& event);
	void OnLeftMouseDown(wxMouseEvent& event);
	void OnLeftMouseUp(wxMouseEvent& event);
	void OnMouseMotion(wxMouseEvent& event);
	// event handling macro
	DECLARE_EVENT_TABLE()
};
}

#endif // SAFADER_H
