//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard

#ifndef MONITORNODEWIDGET_H
#define MONITORNODEWIDGET_H

#include "pvarwidgets.h"

namespace Resound
{
enum MNW_ID
{
    MNW_LABEL,
    MNW_METER,
    MNW_LOCKBUTTON
};
// A single node gui object contains various controls for editing
// a single matrix parameter node
class MonitorNodeWidget : public ParameterAddressWidgetBase
{
public:
	// class constructor
	MonitorNodeWidget(wxWindow* parent, int id, ParameterAddress _addr);
	// class destructor
	~MonitorNodeWidget();
private:
	int m_lastY;
	// event handlers
	void OnLeftMouseDown(wxMouseEvent& event);
	void OnLeftMouseMove(wxMouseEvent& event);
	void OnLeftMouseUp(wxMouseEvent& event);
	void OnRightMouseUp(wxMouseEvent& event);
	void OnLockToggle(wxCommandEvent& event);
	Resound::ParameterVUMeterWidget *meter;
	wxString label;
	// event handling macro
	DECLARE_EVENT_TABLE()
};
}

#endif // MONITORNODEWIDGET_H
