//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard

#ifndef MONITORVIEW_H
#define MONITORVIEW_H



namespace SA
{

// monitor viewing and control class
class MonitorView : public wxScrolledWindow
{
public:
	// class constructor
	MonitorView(wxWindow* parent, int id, AMClient* _amClient);
	// class destructor
	~MonitorView();

	void Rebuild();

private:
	wxScrolledWindow* scroll;
	AMClient* amClient;

	// event handling macro
	DECLARE_EVENT_TABLE()
};

}
#endif // MONITORVIEW_H
