//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard
#include "pch.h" // precompiler header

#include "automation.h"
#include "pvar.h"
#include "vumeterwidget.h"
#include "monitornodewidget.h" // class's header file

// event table
BEGIN_EVENT_TABLE(SA::MonitorNodeWidget, SA::ParameterAddressWidgetBase)
EVT_TOGGLEBUTTON(MNW_LOCKBUTTON, SA::MonitorNodeWidget::OnLockToggle)
END_EVENT_TABLE()

// class constructor
SA::MonitorNodeWidget::MonitorNodeWidget(wxWindow* parent, int id, ParameterAddress _addr)
		: SA::ParameterAddressWidgetBase(parent,id,_addr)
{
	SetWindowStyle(wxSIMPLE_BORDER | wxCLIP_CHILDREN);
	SetBackgroundColour(wxColour(30,100,150));
	SetForegroundColour(wxColour(255,255,255));

	wxSize size(45,45);
	SetSize(size);
	SetMinSize(size);
	SetMaxSize(size);

	// construct the sub objects and sizer
	wxBoxSizer *topSizer = new wxBoxSizer( wxHORIZONTAL );
	wxBoxSizer *leftSizer = new wxBoxSizer( wxVERTICAL );
	//label = (const char*)ParameterNamespaceManager::GetSingleton().GetParameter(addr).get_name().c_str(); FIXME std::string->wxString conversion
	leftSizer->Add(new wxStaticText(this,MNW_LABEL,label, wxPoint(0,0),wxSize(40,18),wxALIGN_CENTRE),wxSizerFlags(0).Align(0).Border(wxALL,0));
	leftSizer->Add(new wxToggleButton(this,MNW_LOCKBUTTON,_("L"), wxPoint(0,0),wxSize(20,20)),wxSizerFlags(0).Center().Border(wxALL,0));
	topSizer->Add(leftSizer);
	meter = new SA::ParameterVUMeterWidget(this,MNW_METER,rand() % 128,0,128,_("image/smMeterOff.png"),_("image/smMeterOn.png"));
	meter->SetTarget(addr);
	topSizer->Add(meter,wxSizerFlags(0).Align(0).Border(wxALL,0)); //meter1
	SetSizer(topSizer);
	//topSizer->SetSizeHints(this);   // set size hints to honour minimum size
	topSizer->Layout();
}

// class destructor
SA::MonitorNodeWidget::~MonitorNodeWidget()
{
	// insert your code here
}

void SA::MonitorNodeWidget::OnLockToggle(wxCommandEvent& event)
{

	bool isSelected = event.IsChecked();
	if(isSelected) {
		ParameterNamespaceManager::GetSingleton().GetParameter(GetAddress())->lock(128); //FIXME note use of 128 constant here?
	} else {
		ParameterNamespaceManager::GetSingleton().GetParameter(GetAddress())->unlock();
	}
}
