//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard
#include "pch.h" // precompiler header

#include "automation.h"
#include "pvar.h"
#include "vumeterwidget.h"
#include "faderwidget.h"
#include "pvarwidgets.h"
#include "masterfader.h"
#include "performanceview.h" // class's header file

// event table
BEGIN_EVENT_TABLE(Resound::PerformanceView, wxScrolledWindow)
EVT_COMMAND_RANGE(0,127,saEVT_FADER_CHANGED, Resound::PerformanceView::OnFaderMove)
END_EVENT_TABLE()

// class constructor
Resound::PerformanceView::PerformanceView(wxWindow* parent)
		: wxScrolledWindow(parent, wxID_ANY, wxPoint(0,0), wxSize(320,240))
{
	// insert your code here

	wxBoxSizer *topSizer = new wxBoxSizer( wxVERTICAL );
	wxBoxSizer *upperTierSizer = new wxBoxSizer( wxHORIZONTAL );
	wxBoxSizer *lowerTierSizer = new wxBoxSizer( wxHORIZONTAL );

	Resound::MasterFader* temp; // temporary, for storing MasterFaders in fader array.

	int fId = 0;
	int n, g;
	for(n = 0; n < 4; n++) // create top row of MasterFaders
	{
		wxBoxSizer* grp = new wxBoxSizer(wxHORIZONTAL);
		for(g = 0; g < 4; g++)
		{
			temp = new Resound::MasterFader(this,fId++); // create new MasterFader
			masterFaderArray.push_back(temp); // store in array
			grp->Add(temp, wxSizerFlags(1).Align(0).Border(wxALL,1)); // add to GUI
		}
		upperTierSizer->Add(grp, wxSizerFlags(1).Align(0).Border(wxALL,5));
	}
	for(n = 0; n < 4; n++) // create bottom row of MasterFaders
	{
		wxBoxSizer* grp = new wxBoxSizer(wxHORIZONTAL);
		for(g = 0; g < 4; g++)
		{
			temp = new Resound::MasterFader(this,fId++); // create new MasterFader
			masterFaderArray.push_back(temp); // store in array
			grp->Add(temp, wxSizerFlags(1).Align(0).Border(wxALL,1)); // add to GUI
		}
		lowerTierSizer->Add(grp, wxSizerFlags(1).Align(0).Border(wxALL,5));
	}
	topSizer->Add(upperTierSizer);
	topSizer->Add(lowerTierSizer);

	SetSizer(topSizer);
	//topSizer->SetSizeHints(this);   // set size hints to honour minimum size
	topSizer->Layout();
}

// class destructor
Resound::PerformanceView::~PerformanceView()
{
	// insert your code here
}

// automation update for this window // triggers redraw
void Resound::PerformanceView::Tick(float dT)
{}

void Resound::PerformanceView::OnFaderMove(wxCommandEvent& event)
{
	int id = event.GetId();
	int newVal = event.GetInt();
}

void Resound::PerformanceView::Init()
{
	for (int n = 0; n < masterFaderArray.size(); n++) {
		masterFaderArray[n]->SetValue(0);
	}
}


