//   
//   Copyright (c) 2007 David Moore, James Mooney, All Rights Reserved.
//   
//   This program is free software; you can redistribute it and/or
//   modify it under the terms of the GNU General Public License as
//   published by the Free Software Foundation; either version 2 of
//   the License, or (at your option) any later version.
//   
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//   GNU General Public License for more details.
//   
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
//   MA 02111-1307 USA
//   
// Class automatically generated by Dev-C++ New Class wizard

#include "sa_performance.h" // class's header file

namespace SA
{

//---------------------- PVarLockPreset -------------------------------

PVarLockPreset::PVarLockPreset()
{}
PVarLockPreset::~PVarLockPreset()
{}
void PVarLockPreset::Save(wxDateOuputStream& stream)
{}
void PVarLockPreset::Load(wxDateInputStream& stream)
{}

//-------------------- MasterFaderPreset ------------------------------

MasterFaderPreset::MasterFaderPreset()
{}
MasterFaderPreset::~MasterFaderPreset()
{}
void MasterFaderPreset::Save(wxDateOuputStream& stream)
{}
void MasterFaderPreset::Load(wxDateInputStream& stream)
{}

//------------------------- PreformancePreset --------------------------

PerformancePreset::PerformancePreset()
{}
PerformancePreset::~PerformancePreset()
{}
void PerformancePreset::Save(wxDateOuputStream& stream)
{}
void PerformancePreset::Load(wxDateInputStream& stream)
{}

//------------------------- Performance ------------------------------------

Performance::Performance()
{}
Performance::~Performance()
{}
void Performance::Save(wxDateOuputStream& stream)
{}
void Performance::Load(wxDateInputStream& stream)
{}

} // namespace SA
